#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while (( i<=10 ))
do
	if (( i==4))
	then
		printf "bad luck\n"
	elif (( i==8))
	then
		printf "good luck\n"
	else
		printf "Best School\n"
	fi
	(( i+=1 ))
done
