#!/usr/bin/env bash
# displays information about the school file.
for i in {1..100}
do
	if (( i%3==0 ))
	then
		if (( i%5==0 ))
		then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif (( i%5==0 ))
	then
		if (( i%3==0 ))
		then
			echo "FizzBuzz"
		else
			echo "Buzz"
		fi
	else
		echo "$i"
	fi
done
